<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>KoenZomers.Roborock</PackageId>
    <Version>0.3.2.0</Version>
    <Description>Native C# local client for Roborock V1 vacuums.</Description>
    <Authors>Roborock</Authors>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/KoenZomers/Roborock</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>roborock;vacuum;local;client</PackageTags>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>$(MSBuildProjectDirectory)\..\signingkey.key</AssemblyOriginatorKeyFile>
    <RootNamespace>KoenZomers.RoboRock.Api</RootNamespace>
    <AssemblyName>KoenZomers.RoboRock.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildProjectDirectory)\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Library.Tests\**" />
    <EmbeddedResource Remove="Library.Tests\**" />
    <None Remove="Library.Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MQTTnet" Version="5.2.0.1603" />
  </ItemGroup>

</Project>
